import * as ts from "typescript";

export const emitVersionFile = (
	path: string,
	versionInfo: Record<string, string>
) => {
	const statements = Object.entries(versionInfo).map(([key, value]) =>
		ts.factory.createVariableStatement(
			[ts.factory.createModifier(ts.SyntaxKind.ExportKeyword)],
			ts.factory.createVariableDeclarationList(
				[
					ts.factory.createVariableDeclaration(
						ts.factory.createIdentifier(key),
						undefined,
						undefined,
						ts.factory.createStringLiteral(value)
					),
				],
				ts.NodeFlags.Const
			)
		)
	);

	// add leading comment
	ts.addSyntheticLeadingComment(
		statements[0],
		ts.SyntaxKind.SingleLineCommentTrivia,
		" Generated by Kaisaku"
	);

	const nodes = ts.factory.createNodeArray(statements);
	const printer = ts.createPrinter({
		newLine: ts.NewLineKind.LineFeed,
	});
	const result = printer.printList(
		ts.ListFormat.None,
		nodes,
		ts.createSourceFile("version.ts", "", ts.ScriptTarget.Latest)
	);

	return result;
};

